openapi: "3.1.0"
info:
  title: "PhoneBookBackend API"
  description: "PhoneBookBackend API"
  version: "0.1.0-alpha"
servers:
  - url: "http://localhost:8080"
paths:
  /:
    get:
      description: "Ваши стандартные роуты"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "API работает"
  /persons:
    get:
      description: ""
      parameters:
        - name: "lastName"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Person"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат данных"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Person"
  /persons/{id}:
    delete:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат ID"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Пользователь успешно помечен как удаленный"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Пользователь не найден или уже удален"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат ID"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Person"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Пользователь не найден"
    put:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат данных"
                Example#2:
                  value: "Неверный формат ID"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Person"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Пользователь не найден"
  /phones:
    get:
      description: ""
      parameters:
        - name: "personId"
          in: "query"
          required: false
          schema:
            type: "number"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Phone"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PhoneDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат данных"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Phone"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /phones/{id}:
    delete:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат ID"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Телефон успешно удален"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Телефон не найден"
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат ID"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Phone"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Телефон не найден"
    put:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PhoneDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Неверный формат данных"
                Example#2:
                  value: "Неверный формат ID"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Phone"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Телефон не найден"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
components:
  schemas:
    Person:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        firstName:
          type: "string"
        patronymic:
          type: "string"
          nullable: true
        lastName:
          type: "string"
        isDeleted:
          type: "boolean"
      required:
        - "id"
        - "firstName"
        - "lastName"
        - "isDeleted"
    PersonDto:
      type: "object"
      properties:
        firstName:
          type: "string"
        patronymic:
          type: "string"
          nullable: true
        lastName:
          type: "string"
      required:
        - "firstName"
        - "lastName"
    Phone:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        personId:
          type: "integer"
          format: "int64"
        phoneTypeId:
          type: "integer"
          format: "int64"
        countryCode:
          type: "string"
        areaCode:
          type: "string"
        number:
          type: "string"
      required:
        - "id"
        - "personId"
        - "phoneTypeId"
        - "countryCode"
        - "areaCode"
        - "number"
    PhoneDto:
      type: "object"
      properties:
        personId:
          type: "integer"
          format: "int64"
        phoneTypeId:
          type: "integer"
          format: "int64"
        countryCode:
          type: "string"
        areaCode:
          type: "string"
        number:
          type: "string"
      required:
        - "personId"
        - "phoneTypeId"
        - "countryCode"
        - "areaCode"
        - "number"