CREATE TABLE IF NOT EXISTS persons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT    NOT NULL CHECK ( length(trim(first_name)) > 0 ),
    patronymic TEXT,
    last_name  TEXT    NOT NULL CHECK ( length(trim(last_name)) > 0),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

