CREATE TABLE persons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT    NOT NULL CHECK ( length(first_name) > 0 ),
    patronymic TEXT,
    last_name  TEXT    NOT NULL CHECK ( length(last_name) > 0),
    is_deleted BOOLEAN NOT NULL
);


