CREATE TABLE IF NOT EXISTS phone_types
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code TEXT NOT NULL UNIQUE CHECK ( length(trim(type_code)) > 0),
    name      TEXT NOT NULL CHECK ( length(trim(name)) > 0)
);
