CREATE TABLE IF NOT EXISTS person_phones
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id     BIGINT NOT NULL,
    phone_type_id BIGINT NOT NULL,
    country_code  TEXT   NOT NULL CHECK ( country_code ~ '^\+?\d{1,4}$' ),
    area_code     TEXT   NOT NULL CHECK ( area_code ~ '^\(?\d{3,5}\)?$' ),
    number        TEXT   NOT NULL CHECK ( number ~ '^[0-9\-\s]{5,11}$' ),

    CONSTRAINT fk_contacts_person
        FOREIGN KEY (person_id) REFERENCES persons (id) ON DELETE RESTRICT,

    CONSTRAINT fk_contacts_type
        FOREIGN KEY (phone_type_id) REFERENCES phone_types (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_phones_person_id ON person_phones (person_id);
CREATE INDEX IF NOT EXISTS idx_phones_full_number ON person_phones (number);


