CREATE TABLE IF NOT EXISTS audit_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT                     NOT NULL,
    operation  TEXT                     NOT NULL,
    row_id     BIGINT                   NOT NULL,
    old_data   JSONB,
    new_data   JSONB,
    db_user    TEXT                     NOT NULL DEFAULT CURRENT_USER,
    action_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);



CREATE TABLE IF NOT EXISTS persons_history
(
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id  BIGINT                   NOT NULL,
    first_name TEXT                     NOT NULL,
    patronymic TEXT,
    last_name  TEXT                     NOT NULL,
    is_deleted BOOLEAN                  NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS person_phones_history
(
    history_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_id      BIGINT                   NOT NULL,
    person_id     BIGINT                   NOT NULL,
    phone_type_id INT                      NOT NULL,
    country_code  TEXT                     NOT NULL,
    area_code     TEXT                     NOT NULL,
    number        TEXT                     NOT NULL,
    changed_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);


